Repository SABRE-JS/SABRE.js, pull requests merged in 2022-10, with the labels that each got.

#65 Small fixes to the code.
  src/canvas-2d-text-renderer.js
  src/shaders/positioning.fragment.glsl
Labels: minor

#67 Revert bad antialiasing fix.
  src/canvas-2d-text-renderer.js
Labels: bug

#69 Added initial tests for subtitle parser.
  src/__tests__/parser.test.js
  src/__tests__/testfiles/test1.ass
  src/__tests__/testfiles/test2.ass
  src/subtitle-parser.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#71 Added tests for substation alpha.
  src/__tests__/parser.test.js
  src/__tests__/testfiles/test1.ass
  src/__tests__/testfiles/test1.ssa
  src/__tests__/testfiles/test2.ass
  src/__tests__/testfiles/test2.ssa
  src/subtitle-parser.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted
